sudo: required
services:
  - docker

before_install:
  - docker build -t greenlime21/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true greenlime21/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-665986827276"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
  